# Chat with Tools Framework - Minimal Configuration
# ===================================================
# This is a minimal configuration to get started quickly.
# For all available options, see config.full.yaml

# OpenRouter API Configuration
openrouter:
  # Get your API key at: https://openrouter.ai/keys
  # Or set via environment variable: OPENROUTER_API_KEY
  api_key: "YOUR API KEY HERE"
  
  # For local vLLM, use: http://localhost:8000/v1
  base_url: "https://openrouter.ai/api/v1"
  
  # Choose your model:
  #   Fast & Cheap: openai/gpt-4o-mini
  #   Balanced: anthropic/claude-3.5-sonnet
  #   Best: anthropic/claude-3-opus
  model: "openai/gpt-4o-mini"
  
  temperature: 0.7
  max_tokens: 2000

# System prompt for the agent
system_prompt: |
  You are a helpful AI assistant with access to various tools.
  Use tools when needed for calculations, searches, or file operations.
  When you complete a task, call the mark_task_complete tool.

# Basic agent settings
agent:
  max_iterations: 10
  temperature: 0.7

# Multi-agent orchestrator (for council mode)
orchestrator:
  parallel_agents: 4
  task_timeout: 300

# Basic logging
logging:
  level: "INFO"
  console:
    enabled: true
    colored: true

# Essential tool settings
tools:
  search:
    max_results: 5
    engine: "duckduckgo"
  
  file:
    sandbox_dir: "./workspace"
    max_file_size: 10485760  # 10MB
  
  python_executor:
    timeout: 5
    max_memory_mb: 100
    allow_imports: true
  
  memory:
    storage_path: "./agent_memory"
    max_memories: 1000

# Basic performance settings
performance:
  connection_pooling: true
  collect_metrics: false
  max_concurrent_tools: 3

# Essential security settings
security:
  validate_input: true
  max_input_length: 10000
